refactor: clean up YAML workflows by standardizing formatting and improving debug messages

diff --git a/.github/workflows/main-publish.yml b/.github/workflows/main-publish.yml
--- a/.github/workflows/main-publish.yml
+++ b/.github/workflows/main-publish.yml
@@ -9,7 +9,6 @@ on:
 
 jobs:
   publish-main:
-  
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -25,25 +24,24 @@ jobs:
             echo "::set-output name=is_changeset_commit::false"
           fi
 
-
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: "20"
           registry-url: "https://registry.npmjs.org"
-          cache: 'pnpm'
+          cache: "pnpm"
 
       - name: Install pnpm
         run: npm install -g pnpm@10.28.0
 
       - name: Debug pnpm version
         run: |
-          echo 'Vérification de pnpm:'
-          which pnpm || { echo 'pnpm introuvable'; exit 1; }
+          echo 'check pnpm:'
+          which pnpm || { echo 'pnpm not found'; exit 1; }
           pnpm --version
 
       - name: Install dependencies
-        run: pnpm install
+        run: pnpm install --no-frozen-lockfile
 
       - name: Generate Changesets
         env:
@@ -85,8 +83,6 @@ jobs:
           npx changeset publish --tag latest
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-
-
 
       - name: Install pnpm
         run: npm install -g pnpm@10.28.0
diff --git a/.github/workflows/next-publish.yml b/.github/workflows/next-publish.yml
--- a/.github/workflows/next-publish.yml
+++ b/.github/workflows/next-publish.yml
@@ -12,12 +12,12 @@ on:
 
 jobs:
   publish-dev:
-    runs-on: ubuntu-latest 
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      
+
       - name: Check commit message
         id: check_message
         run: |
@@ -35,19 +35,19 @@ jobs:
 
       - name: Debug pnpm version
         run: |
-          echo 'Vérification de pnpm:'
-          which pnpm || { echo 'pnpm introuvable'; exit 1; }
+          echo 'check pnpm:'
+          which pnpm || { echo 'pnpm not found'; exit 1; }
           pnpm --version
 
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '20'
-          cache: 'pnpm'
-          registry-url: 'https://registry.npmjs.org'
-          
+          node-version: "20"
+          cache: "pnpm"
+          registry-url: "https://registry.npmjs.org"
+
       - name: Install dependencies
-        run: pnpm install
+        run: pnpm install --no-frozen-lockfile
 
       - name: Generate Changesets
         env:
